/**
 * Sytax Exception
 */
//console.log("hello";


/**
 * Runtime exception
 */
 let x=5
 console.log();
/**
 * Logical exception
 */
 let num=5
 for(i=-3;i<5;i++){
    console.log(num/i); // logical error is divide by 0
 }
